AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  random-bot-app

  Sample random-bot-app
Globals:
  Function:
    Timeout: 10

Resources:
  RandomBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        RandomBot:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        RandomBotPost:
          Type: Api
          Properties:
            Path: /hello
            Method: post
      Environment:
        Variables:
          SLACK_BOT_OAUTH_TOKEN: xyz
          SLACK_SIGNIN_SECRET: xyz
          NOTION_SECRET: xyz
          NOTION_HEXAGRAMS_TABLE_ID: xyz
          NOTION_QUESTIONS_TABLE_ID: xyz
          CHANNEL_GENERAL_ID: xyz
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  RandomBotApi:
    Description: "API Gateway endpoint URL for Prod stage for RandomBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RandomBotFunction:
    Description: "RandomBot Lambda Function ARN"
    Value: !GetAtt RandomBotFunction.Arn
  RandomBotFunctionIamRole:
    Description: "Implicit IAM Role created for RandomBot function"
    Value: !GetAtt RandomBotFunctionRole.Arn
